"""Configuration constants for broadcast execution timings."""

BROADCAST_BATCH_SIZE = 20
BROADCAST_DELAY_MIN_SECONDS = 4
BROADCAST_DELAY_MAX_SECONDS = 9
BROADCAST_BATCH_PAUSE_SECONDS = 20

__all__ = [
    "BROADCAST_BATCH_SIZE",
    "BROADCAST_DELAY_MIN_SECONDS",
    "BROADCAST_DELAY_MAX_SECONDS",
    "BROADCAST_BATCH_PAUSE_SECONDS",
]
